version: "3.9"

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php-first-mySQL